### PR TITLE
Created Secret token validator middleware

### PR DESCRIPTION
**Pull request by BlueXTX**
resolve issue #1112

### CODE REVIEW

**Comment by BlueXTX** [comment]
resolve #1190

**Comment by karb0f0s** [comment]
First of all, @BlueXTX thank you for your contribution!
Though I have a few concerns about this change:
* The biggest issue is ASP.NET dependencies. I'm not sure how they play out for legacy platforms, covered by .netstandard2.0 target. It might be safer to introduce this change under `#if DOTNET6_OR_GREATER` directive to avoid collision with older .NET frameworks.
* I don't see a way to differentiate between controllers for this middleware. If I have other endpoints in my app, they would require `X-Telegram-Bot-Api-Secret-Token` header too.
* IMO helper functions and middleware classes would greatly benefit from some level of XML documentation on them.

@tuscen WDYT?

**Comment by BlueXTX** [comment]
> First of all, @BlueXTX thank you for your contribution! Though I have a few concerns about this change:
> 
> * The biggest issue is ASP.NET dependencies. I'm not sure how they play out for legacy platforms, covered by .netstandard2.0 target. It might be safer to introduce this change under `#if DOTNET6_OR_GREATER` directive to avoid collision with older .NET frameworks.
> * I don't see a way to differentiate between controllers for this middleware. If I have other endpoints in my app, they would require `X-Telegram-Bot-Api-Secret-Token` header too.
> * IMO helper functions and middleware classes would greatly benefit from some level of XML documentation on them.
> 
> @tuscen WDYT?

1. [Microsoft.Extensions.Options](https://www.nuget.org/packages/Microsoft.Extensions.Options/#supportedframeworks-body-tab) and [Microsoft.AspNetCore.Http.Abstractions](https://www.nuget.org/packages/Microsoft.AspNetCore.Http.Abstractions/#supportedframeworks-body-tab) have support for netstandard2.0. 
2. Will it be enough if I add configuration like this? `app.UseWhen(context => context.Request.Path.StartsWithSegments("/YourPath"), appBuilder =>
        {
            appBuilder.UseMiddleware<SecretTokenValidatorMiddleware>();
        });`

**Comment by tuscen** [comment]
I don't think we should take dependency on M.E.x libraries in the core package. It's ok to make a separate package for ASP.NET Core integration though.

**Comment by wiz0u** [comment]
Thanks for your contribution @BlueXTX 
For now, I think it's simpler to do without such middleware (see #1112)

**Pull request closed without merging**
