### PR TITLE
Fix issue #431

### PR DESCRIPTION
**Pull request by Olfi01**

### CODE REVIEW

**Comment by Olfi01** [comment]
i would really much like this to be added to nuget asap xD until then i guess i'll have to upload my own private package

**Comment by pouladpld** [comment]
@Olfi01 Thank you for the PR.

Unfortunately, I won't get a chance to work on this till Saturday. I also might not merge this without adding one or two related test cases.

So could you add tests for this as well?

**Comment by Olfi01** [comment]
err actually i can try but i found a workaround so its not that important rn
but yeah if i got time ill write a test
im just not feeling very well rn

**Comment by Olfi01** [comment]
actually i dont rly know how to add a test xD

**Comment by Olfi01** [comment]
nvm, i found out

**Comment by pouladpld** [comment]
Serialization test scenarios are a great candidate to be in a Unit Test project.

We do not really need to call the API(Systems Integration Testing) for doing this.

Maybe this goes to `Telegram.Bot.UnitTests` project.

**Comment by Olfi01** [comment]
if you say so. so what should i do?

**Comment by pouladpld** [comment]
That's what makes sense to me and yes, would be great if you start it.

I'll continue with your work this weekend.

**Comment by Olfi01** [comment]
i actually dont really get it... i should add a new unittest project? i'll see if i got time... i'm a bit busy rn.

**Comment by pouladpld** [comment]
Ya. Another xunit test project.

**Comment by pouladpld** [comment]
@Olfi01 Thank you for the PR. I merged it manually(fix commit only) and added a unit test project testing serialization of document message.

<https://github.com/TelegramBots/telegram.bot/commit/41ceddb3a0eb583ae28a1ce7cda1ddde1626d4f5>

**Pull request closed without merging**
