### PR TITLE
Tests with proxy

### PR DESCRIPTION
**Pull request by karb0f0s**
- add socks5 proxy support in `TestsFixture`

### CODE REVIEW

**Comment by karb0f0s** [comment]
.gitmodules format was wrong and i had to add `- git submodule update --init --recursive` step to pull submodule code from external repository

**Comment by karb0f0s** [comment]
This class is not available as nuget package :(. Other nuget libs I tried do not provide socks5 proxy functionality.

**Comment by MihaZupan** [comment]
The library is now available on NuGet: https://www.nuget.org/packages/HttpToSocks5Proxy/

**Comment by karb0f0s** [comment]
I found a way to run tests without proxy, can I close this PR now?

**Pull request closed without merging**
