### PR TITLE
Add constructor for Local Bot API Server

### PR DESCRIPTION
**Pull request by zefir01**
This is need to use Local Bot API Server (https://core.telegram.org/bots/api#using-a-local-bot-api-server) or for use a reverse proxy.

### CODE REVIEW

**Comment by Fedorus** [comment]
1. It is already implemented in 5.0+ version
2. It is not working correctly with files.

**Comment by zefir01** [comment]
It is not working correctly with files.
Not working correctly with files in 5.0+ version? or in my request?

**Comment by Fedorus** [comment]
In your PR. 
Cuz with --local you will get local path to file on your PC instead of https link to telegram servers and that will break few method in the library

**Comment by zefir01** [comment]
ok. i got it. sorry.

**Pull request closed without merging**
