### PR TITLE
fix: #1036 delete webhook request ignore request body

### PR DESCRIPTION
**Pull request by AKomyshan**
fix https://github.com/TelegramBots/Telegram.Bot/issues/1036

### CODE REVIEW

**Comment by karb0f0s** [comment]
@AKomyshan good catch! thank you for your contribution.

**Review by karb0f0s — APPROVED** [review]

**Comment by AKomyshan** [comment]
@karb0f0s can you merge this PR? I am ok with your commit

**Review by karb0f0s — APPROVED** [review]

**Comment by AKomyshan** [comment]
@karb0f0s Hi, any updates?

**Comment by karb0f0s** [comment]
I can't pass the test :( 
@tuscen - can you help?

**Pull request merged**
