### PR TITLE
Override method Equals for User

### PR DESCRIPTION
**Pull request by Quantum-0**

### CODE REVIEW

**Comment by mhverbakel** [comment]
I disapprove this. Only checking the id property is not enough, because two user objects with different properties might be deemed unequal in some existing applications, which would be broken by them suddenly be equal.

That aside, overriding equals also means overriding GetHashCode.

**Comment by Olfi01** [comment]
i actually agree with mhverbakel, two user objects aren't the same if they have the same ID. If you wanna check whether it's the same person, just go on and compare the IDs yourself.

**Comment by Olfi01** [comment]
@Quantum-0 how about this?
```c#
User.Is(User u) => u.Id == this.Id
```

**Comment by pouladpld** [comment]
How about adding a few useful extension methods for frequent comparisons instead?

```c#
// extension methods in Telegram.Bot namespace

bool isSameUser = someUser.IdEquals(otherUser);
bool hasSameSender = someUpdate.IsFromSameUserId(otherUser); // for messages, channel posts, callback query,...
int? msgId = someUpdate.TryGetMessageId(); // for messages, channel posts, callback query,...
long? chatId = someUpdate.TryGetChatId(); // for messages, channel posts, callback query,...
string idOrNull = someUpdate.TryGetCallbackQueryId();
```

**Comment by Olfi01** [comment]
I guess this can be closed? I have opened #442 for discussion instead

**Comment by pouladpld** [comment]
@Quantum-0 I'm closing this PR as we planning to add extension methods for this purpose. Feel free to join our discussion in #442

**Pull request closed without merging**
