### PR TITLE
Azure DevOps code coverage

### PR DESCRIPTION
**Pull request by karb0f0s**
Code coverage for Azure DevOps

### CODE REVIEW

**Comment by karb0f0s** [comment]
image

**Comment by tuscen** [comment]
Can this be done without using DotNetCLI task?

**Comment by karb0f0s** [comment]
Idk, why?

**Comment by wiz0u** [comment]
What's the point in having DevOps tell us our code coverage is 33% ?
It's likely not testing any inbound Update handling code from our Integ test suite as it can't see Telegram interactions.

Moreover, we don't have the workforce to improve code coverage anyway...
So I'm considering closing this PR.

**Pull request closed without merging**
