### PR TITLE
vNext draft

### PR DESCRIPTION
**Pull request by MihaZupan**
Major changes:
- [X] Target netstandard2.0 (allows us to remove `System.Net.Requests` as a dependency)
- [X] Remove polling events (replaced by extension package `Telegram.Bot.Extensions.Polling`)
- [X] Remove code marked as obsolete pre-v15
- [x] Remove exception parsing from core package
- [x] Fix parameter order (CT back to the end) / Use Request object

Minor:
- [X] Fix caption descriptions (#807)
- [x] Fix parameter types in `InputMediaAudio` (title, performer)
- [ ] File download overloads
- [x] Use doubles for coordinates?
- [x] Fix compilation warnings
- [x] Address ToDo comments
- [x] Review skipped test cases
- [x] Make test method styles look consistent
- [ ] Assembly signing
- [ ] Update the book and examples accordingly
- [x] Use C# 8 and enable nullable references

Under discussion:
- [ ] Use Request objects instead of parameter spaghetti

### CODE REVIEW

**Comment by tuscen** [comment]
There're a few methods with inconsistent order of params. I think they should be fixed since it's major version bump.

https://github.com/TelegramBots/Telegram.Bot/blob/85134a4b5f09de4bef4306aa44d708c202b31f31/src/Telegram.Bot/ITelegramBotClient.cs#L345
https://github.com/TelegramBots/Telegram.Bot/blob/85134a4b5f09de4bef4306aa44d708c202b31f31/src/Telegram.Bot/ITelegramBotClient.cs#L377
https://github.com/TelegramBots/Telegram.Bot/blob/85134a4b5f09de4bef4306aa44d708c202b31f31/src/Telegram.Bot/ITelegramBotClient.cs#L436
https://github.com/TelegramBots/Telegram.Bot/blob/85134a4b5f09de4bef4306aa44d708c202b31f31/src/Telegram.Bot/ITelegramBotClient.cs#L531
https://github.com/TelegramBots/Telegram.Bot/blob/85134a4b5f09de4bef4306aa44d708c202b31f31/src/Telegram.Bot/ITelegramBotClient.cs#L622
https://github.com/TelegramBots/Telegram.Bot/blob/85134a4b5f09de4bef4306aa44d708c202b31f31/src/Telegram.Bot/ITelegramBotClient.cs#L976

**Comment by poulad** [comment]
Adding on to the draft:

- Fix compilation warning
- Address ToDo comments
- Review skipped test cases
- Make test method styles look consistent
- Update the book accordingly

**Comment by MihaZupan** [comment]
@tuscen What I meant by `File download overloads` was something along the lines of https://github.com/TelegramBots/Telegram.Bot/pull/771/files#diff-b291906956a2aad4a17a2660a9c12d8fR104

**Comment by tuscen** [comment]
Adding on to the draft:
- [ ] Add to `IRequest<T>` interface property `bool IsWebhookResponse { get; set; }`

**Comment by tuscen** [comment]
Discussion:
- [ ] Why does `User` implements `IEquatable`? Two users are equal when their `Id` is equal, that's it. And I think we shouldn't provide equality method for Bot API types.

**Comment by MihaZupan** [comment]
Would be useful for user lookups in a dictionary to avoid matching with object reference equality

**Comment by tuscen** [comment]
I think it's time to close this PR since most changes have been released in v17.

**Pull request closed without merging**
