### PR TITLE
Bot API v3.3

### PR DESCRIPTION
**Pull request by pouladpld**
Not all of the changes have been tested yet.

I'd suggest to publish this as version `13.2.2-rc` until the tests are ready.

### CODE REVIEW

**Comment by pouladpld** [comment]
Oh. Just remembered that CHANGELOG, Project file, and README need to be modified as well.

**Comment by pouladpld** [comment]
I updated the `.Core` package based on this PR.

<https://www.nuget.org/packages/Telegram.Bot.Core/13.2.2-rc>

**Comment by Olfi01** [comment]
@MrRoundRobin when will the nuget package be updated?

**Comment by pouladpld** [comment]
@Olfi01 he did it yesterday.

**Comment by Olfi01** [comment]
@pouladpld oh, oops, thanks

**Comment by pouladpld** [comment]
Yes. It finally happened :p

**Comment by Olfi01** [comment]
@pouladpld err, I can't find the package for 3.3 on nuget

**Comment by pouladpld** [comment]
@Olfi01 check pre-release

**Comment by Olfi01** [comment]
@pouladpld oh, beta, thanks

**Pull request merged**
