### PR TITLE
ChatId

### PR DESCRIPTION
**Pull request by Backs**
ChatId validation

### CODE REVIEW

**Comment by tuscen** [comment]
Could you rebase your commit on top current v15? There are more than 200 commits in difference, just in case.

**Comment by Backs** [comment]
Done

**Comment by tuscen** [comment]
Thank you. I'll try merging your PR this week.

**Comment by tuscen** [comment]
You need to replace `Assert.Throws<ArgumentException>` with `Assert.Throws<ArgumentOutOfRangeException>` `ChatIdTests.Invalid_User_Name` test.

**Comment by Backs** [comment]
fixed

**Pull request merged**
